package three
// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// geometry_method_generator -geometryType SphereGeometry -geometrySlug sphere_geometry

import "github.com/gopherjs/gopherjs/js"
	
func (g SphereGeometry) ApplyMatrix(matrix *Matrix4) {
	g.Object.Call("applyMatrix", matrix)
}

func (g SphereGeometry) RotateX() {
	g.Object.Call("rotateX")
}

func (g SphereGeometry) RotateY() {
	g.Object.Call("rotateY")
}

func (g SphereGeometry) RotateZ() {
	g.Object.Call("rotateZ")
}

func (g SphereGeometry) Translate() {
	g.Object.Call("translate")
}

func (g SphereGeometry) Scale() {
	g.Object.Call("scale")
}

func (g SphereGeometry) LookAt() {
	g.Object.Call("lookAt")
}

func (g SphereGeometry) FromBufferGeometry(geometry Geometry) {
	g.Object.Call("fromBufferGeometry")
}

func (g SphereGeometry) Center() {
	g.Object.Call("center")
}

func (g SphereGeometry) Normalize() SphereGeometry {
	g.Object.Call("normalize")
	return g
}

func (g SphereGeometry) ComputeFaceNormals() {
	g.Object.Call("computeFaceNormals")
}

func (g SphereGeometry) ComputeVertexNormals(areaWeighted bool) {
	g.Object.Call("computeVertexNormals", areaWeighted)
}

func (g SphereGeometry) ComputeFlatVertexNormals() {
	g.Object.Call("computeFlatVertexNormals")
}

func (g SphereGeometry) ComputeMorphNormals() {
	g.Object.Call("computeMorphNormals")
}

func (g SphereGeometry) ComputeLineDistances() {
	g.Object.Call("computeLineDistances")
}

func (g SphereGeometry) ComputeBoundingBox() {
	g.Object.Call("computeBoundingBox")
}

func (g SphereGeometry) ComputeBoundingSphere() {
	g.Object.Call("computeBoundingSphere")
}

func (g SphereGeometry) Merge(geometry Geometry, matrix Matrix4, materialIndexOffset float64) {
	g.Object.Call("merge", geometry, matrix, materialIndexOffset)
}

func (g SphereGeometry) MergeMesh(mesh Mesh) {
	g.Object.Call("mergeMesh", mesh.getInternalObject())
}

func (g SphereGeometry) MergeVertices() {
	g.Object.Call("mergeVertices")
}

func (g SphereGeometry) SortFacesByMaterialIndex() {
	g.Object.Call("sortFacesByMaterialIndex")
}

func (g SphereGeometry) ToJSON() interface{} {
	return g.Object.Call("toJSON")
}

// func (g SphereGeometry) Clone() SphereGeometry {
// 	return g.Object.Call("clone")
// }

func (g SphereGeometry) Copy(source Object3D, recursive bool) *SphereGeometry {
	return &SphereGeometry{Object: g.getInternalObject().Call("copy", source.getInternalObject(), recursive)}
}

func (g SphereGeometry) Dispose() {
	g.Object.Call("dispose")
}

func (g SphereGeometry) getInternalObject() *js.Object {
	return g.Object
}

