package three
// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// object3d_method_generator -typeName TextSprite -typeSlug text_sprite

import "github.com/gopherjs/gopherjs/js"

func (obj *TextSprite) ApplyMatrix(matrix *Matrix4) {
	obj.Call("applyMatrix", matrix)
}

func (obj *TextSprite) Add(m Object3D) {
	obj.Object.Call("add", m)
}

func (obj *TextSprite) Remove(m *js.Object) {
	obj.Object.Call("remove", m)
}

func (obj *TextSprite) GetObjectById(id int) *js.Object {
	return obj.Call("getObjectById", id)
}

// func (obj *TextSprite) Copy() *TextSprite {
// 	return &TextSprite{Object: obj.getInternalObject().Call("copy")}
// }

func (obj *TextSprite) ToJSON() interface{} {
	return obj.Object.Call("toJSON").Interface()
}

func (obj *TextSprite) getInternalObject() *js.Object {
	return obj.Object
}

func (obj *TextSprite) UpdateMatrix() {
	obj.Call("updateMatrix")
}

