package three
// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// object3d_method_generator -typeName Line -typeSlug line

import "github.com/gopherjs/gopherjs/js"

func (obj *Line) ApplyMatrix(matrix *Matrix4) {
	obj.Call("applyMatrix", matrix)
}

func (obj *Line) Add(m Object3D) {
	obj.Object.Call("add", m)
}

func (obj *Line) Remove(m *js.Object) {
	obj.Object.Call("remove", m)
}

func (obj *Line) GetObjectById(id int) *js.Object {
	return obj.Call("getObjectById", id)
}

// func (obj *Line) Copy() *Line {
// 	return &Line{Object: obj.getInternalObject().Call("copy")}
// }

func (obj *Line) ToJSON() interface{} {
	return obj.Object.Call("toJSON").Interface()
}

func (obj *Line) getInternalObject() *js.Object {
	return obj.Object
}

