package three
// Code generated by go generate; DO NOT EDIT.
//
// using the following cmd:
// object3d_method_generator -typeName Fog -typeSlug fog

import "github.com/gopherjs/gopherjs/js"

func (obj *Fog) ApplyMatrix(matrix *Matrix4) {
	obj.Call("applyMatrix", matrix)
}

func (obj *Fog) Add(m Object3D) {
	obj.Object.Call("add", m)
}

func (obj *Fog) Remove(m *js.Object) {
	obj.Object.Call("remove", m)
}

func (obj *Fog) GetObjectById(id int) *js.Object {
	return obj.Call("getObjectById", id)
}

// func (obj *Fog) Copy() *Fog {
// 	return &Fog{Object: obj.getInternalObject().Call("copy")}
// }

func (obj *Fog) ToJSON() interface{} {
	return obj.Object.Call("toJSON").Interface()
}

func (obj *Fog) getInternalObject() *js.Object {
	return obj.Object
}

func (obj *Fog) UpdateMatrix() {
	obj.Call("updateMatrix")
}

